"""Central runtime limits for Mind delegation flows."""

MAX_STREAM_EVENTS = 250
MAX_TEXT_DELTA_EVENTS = 4000

MAX_AUTOSAVE_MEMORIES_PER_RUN = 1
MAX_AUTOSAVE_INSIGHTS_PER_RUN = 1

MAX_MEMORY_CONTEXT_ITEMS = 16
MAX_FEEDBACK_CONTEXT_ITEMS = 4
MAX_IMPLICIT_CONTEXT_ITEMS = 4
MAX_INSIGHT_CONTEXT_ITEMS = 4

DEFAULT_MIND_MAX_TURNS = 40
DEFAULT_SPAWN_MAX_CALLS = 3
DEFAULT_SPAWN_MAX_TURNS = 20
DEFAULT_MEMORY_SAVE_MAX_CALLS = 12
